inherit_gem:
  rubocop-standard:
    - config/default.yml

plugins:
  - rubocop-rspec

Naming/FileName:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

# RSpec/SpecFilePathFormat:
#   Enabled: false

# RSpec/SpecFilePathSuffix:
#   Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
