name: Release

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  ruby:
    uses: yettoapp/actions/.github/workflows/ruby_gem_release.yml@main
    secrets:
      rubygems_api_key: ${{ secrets.RUBYGEMS_API_BOT_KEY }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      gem_name: html-proofer
      version_filepath: lib/html_proofer/version.rb
      labeled: ${{ github.event.label.name == 'release' }}
      release: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release') }}
